/*
 * API Marketplace Grupo Netshoes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse200ItemsAttributes;
import io.swagger.client.model.InlineResponse200ItemsImages;
import io.swagger.client.model.InlineResponse200ItemsLinks;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200Items
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T17:28:46.190Z")
public class InlineResponse200Items {
  @SerializedName("expands")
  private List<String> expands = new ArrayList<String>();

  @SerializedName("sku")
  private String sku = null;

  @SerializedName("productGroup")
  private String productGroup = null;

  @SerializedName("department")
  private String department = null;

  @SerializedName("productType")
  private String productType = null;

  @SerializedName("brand")
  private String brand = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("flavor")
  private String flavor = null;

  @SerializedName("gender")
  private String gender = null;

  @SerializedName("manufacturerCode")
  private String manufacturerCode = null;

  @SerializedName("size")
  private String size = null;

  @SerializedName("eanIsbn")
  private String eanIsbn = null;

  @SerializedName("height")
  private Double height = null;

  @SerializedName("width")
  private Double width = null;

  @SerializedName("depth")
  private Double depth = null;

  @SerializedName("weight")
  private Double weight = null;

  @SerializedName("video")
  private String video = null;

  @SerializedName("images")
  private List<InlineResponse200ItemsImages> images = new ArrayList<InlineResponse200ItemsImages>();

  @SerializedName("attributes")
  private List<InlineResponse200ItemsAttributes> attributes = new ArrayList<InlineResponse200ItemsAttributes>();

  @SerializedName("links")
  private List<InlineResponse200ItemsLinks> links = new ArrayList<InlineResponse200ItemsLinks>();

  public InlineResponse200Items expands(List<String> expands) {
    this.expands = expands;
    return this;
  }

  public InlineResponse200Items addExpandsItem(String expandsItem) {
    this.expands.add(expandsItem);
    return this;
  }

   /**
   * Get expands
   * @return expands
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getExpands() {
    return expands;
  }

  public void setExpands(List<String> expands) {
    this.expands = expands;
  }

  public InlineResponse200Items sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public InlineResponse200Items productGroup(String productGroup) {
    this.productGroup = productGroup;
    return this;
  }

   /**
   * Get productGroup
   * @return productGroup
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductGroup() {
    return productGroup;
  }

  public void setProductGroup(String productGroup) {
    this.productGroup = productGroup;
  }

  public InlineResponse200Items department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public InlineResponse200Items productType(String productType) {
    this.productType = productType;
    return this;
  }

   /**
   * Get productType
   * @return productType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductType() {
    return productType;
  }

  public void setProductType(String productType) {
    this.productType = productType;
  }

  public InlineResponse200Items brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public InlineResponse200Items name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse200Items description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InlineResponse200Items color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public InlineResponse200Items flavor(String flavor) {
    this.flavor = flavor;
    return this;
  }

   /**
   * Get flavor
   * @return flavor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFlavor() {
    return flavor;
  }

  public void setFlavor(String flavor) {
    this.flavor = flavor;
  }

  public InlineResponse200Items gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public InlineResponse200Items manufacturerCode(String manufacturerCode) {
    this.manufacturerCode = manufacturerCode;
    return this;
  }

   /**
   * Get manufacturerCode
   * @return manufacturerCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getManufacturerCode() {
    return manufacturerCode;
  }

  public void setManufacturerCode(String manufacturerCode) {
    this.manufacturerCode = manufacturerCode;
  }

  public InlineResponse200Items size(String size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSize() {
    return size;
  }

  public void setSize(String size) {
    this.size = size;
  }

  public InlineResponse200Items eanIsbn(String eanIsbn) {
    this.eanIsbn = eanIsbn;
    return this;
  }

   /**
   * Get eanIsbn
   * @return eanIsbn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEanIsbn() {
    return eanIsbn;
  }

  public void setEanIsbn(String eanIsbn) {
    this.eanIsbn = eanIsbn;
  }

  public InlineResponse200Items height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public InlineResponse200Items width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }

  public InlineResponse200Items depth(Double depth) {
    this.depth = depth;
    return this;
  }

   /**
   * Get depth
   * @return depth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getDepth() {
    return depth;
  }

  public void setDepth(Double depth) {
    this.depth = depth;
  }

  public InlineResponse200Items weight(Double weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public InlineResponse200Items video(String video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVideo() {
    return video;
  }

  public void setVideo(String video) {
    this.video = video;
  }

  public InlineResponse200Items images(List<InlineResponse200ItemsImages> images) {
    this.images = images;
    return this;
  }

  public InlineResponse200Items addImagesItem(InlineResponse200ItemsImages imagesItem) {
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse200ItemsImages> getImages() {
    return images;
  }

  public void setImages(List<InlineResponse200ItemsImages> images) {
    this.images = images;
  }

  public InlineResponse200Items attributes(List<InlineResponse200ItemsAttributes> attributes) {
    this.attributes = attributes;
    return this;
  }

  public InlineResponse200Items addAttributesItem(InlineResponse200ItemsAttributes attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse200ItemsAttributes> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<InlineResponse200ItemsAttributes> attributes) {
    this.attributes = attributes;
  }

  public InlineResponse200Items links(List<InlineResponse200ItemsLinks> links) {
    this.links = links;
    return this;
  }

  public InlineResponse200Items addLinksItem(InlineResponse200ItemsLinks linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse200ItemsLinks> getLinks() {
    return links;
  }

  public void setLinks(List<InlineResponse200ItemsLinks> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Items inlineResponse200Items = (InlineResponse200Items) o;
    return Objects.equals(this.expands, inlineResponse200Items.expands) &&
        Objects.equals(this.sku, inlineResponse200Items.sku) &&
        Objects.equals(this.productGroup, inlineResponse200Items.productGroup) &&
        Objects.equals(this.department, inlineResponse200Items.department) &&
        Objects.equals(this.productType, inlineResponse200Items.productType) &&
        Objects.equals(this.brand, inlineResponse200Items.brand) &&
        Objects.equals(this.name, inlineResponse200Items.name) &&
        Objects.equals(this.description, inlineResponse200Items.description) &&
        Objects.equals(this.color, inlineResponse200Items.color) &&
        Objects.equals(this.flavor, inlineResponse200Items.flavor) &&
        Objects.equals(this.gender, inlineResponse200Items.gender) &&
        Objects.equals(this.manufacturerCode, inlineResponse200Items.manufacturerCode) &&
        Objects.equals(this.size, inlineResponse200Items.size) &&
        Objects.equals(this.eanIsbn, inlineResponse200Items.eanIsbn) &&
        Objects.equals(this.height, inlineResponse200Items.height) &&
        Objects.equals(this.width, inlineResponse200Items.width) &&
        Objects.equals(this.depth, inlineResponse200Items.depth) &&
        Objects.equals(this.weight, inlineResponse200Items.weight) &&
        Objects.equals(this.video, inlineResponse200Items.video) &&
        Objects.equals(this.images, inlineResponse200Items.images) &&
        Objects.equals(this.attributes, inlineResponse200Items.attributes) &&
        Objects.equals(this.links, inlineResponse200Items.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expands, sku, productGroup, department, productType, brand, name, description, color, flavor, gender, manufacturerCode, size, eanIsbn, height, width, depth, weight, video, images, attributes, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Items {\n");
    
    sb.append("    expands: ").append(toIndentedString(expands)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    productGroup: ").append(toIndentedString(productGroup)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    productType: ").append(toIndentedString(productType)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    flavor: ").append(toIndentedString(flavor)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    manufacturerCode: ").append(toIndentedString(manufacturerCode)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    eanIsbn: ").append(toIndentedString(eanIsbn)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

