/*
 * API Marketplace Grupo Netshoes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse200ItemsLinks;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T17:28:46.190Z")
public class InlineResponse2002 {
  @SerializedName("listPrice")
  private Double listPrice = null;

  @SerializedName("salePrice")
  private Double salePrice = null;

  @SerializedName("links")
  private List<InlineResponse200ItemsLinks> links = new ArrayList<InlineResponse200ItemsLinks>();

  public InlineResponse2002 listPrice(Double listPrice) {
    this.listPrice = listPrice;
    return this;
  }

   /**
   * Get listPrice
   * @return listPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getListPrice() {
    return listPrice;
  }

  public void setListPrice(Double listPrice) {
    this.listPrice = listPrice;
  }

  public InlineResponse2002 salePrice(Double salePrice) {
    this.salePrice = salePrice;
    return this;
  }

   /**
   * Get salePrice
   * @return salePrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSalePrice() {
    return salePrice;
  }

  public void setSalePrice(Double salePrice) {
    this.salePrice = salePrice;
  }

  public InlineResponse2002 links(List<InlineResponse200ItemsLinks> links) {
    this.links = links;
    return this;
  }

  public InlineResponse2002 addLinksItem(InlineResponse200ItemsLinks linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse200ItemsLinks> getLinks() {
    return links;
  }

  public void setLinks(List<InlineResponse200ItemsLinks> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.listPrice, inlineResponse2002.listPrice) &&
        Objects.equals(this.salePrice, inlineResponse2002.salePrice) &&
        Objects.equals(this.links, inlineResponse2002.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listPrice, salePrice, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    listPrice: ").append(toIndentedString(listPrice)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

