/*
 * API Marketplace Grupo Netshoes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001Reviews;
import java.util.ArrayList;
import java.util.List;

/**
 * ProductStatusResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T17:28:46.190Z")
public class ProductStatusResponse {
  @SerializedName("status")
  private String status = null;

  @SerializedName("reviews")
  private List<InlineResponse2001Reviews> reviews = new ArrayList<InlineResponse2001Reviews>();

  public ProductStatusResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ProductStatusResponse reviews(List<InlineResponse2001Reviews> reviews) {
    this.reviews = reviews;
    return this;
  }

  public ProductStatusResponse addReviewsItem(InlineResponse2001Reviews reviewsItem) {
    this.reviews.add(reviewsItem);
    return this;
  }

   /**
   * Get reviews
   * @return reviews
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2001Reviews> getReviews() {
    return reviews;
  }

  public void setReviews(List<InlineResponse2001Reviews> reviews) {
    this.reviews = reviews;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductStatusResponse productStatusResponse = (ProductStatusResponse) o;
    return Objects.equals(this.status, productStatusResponse.status) &&
        Objects.equals(this.reviews, productStatusResponse.reviews);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, reviews);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductStatusResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reviews: ").append(toIndentedString(reviews)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

