/*
 * API Marketplace Grupo Netshoes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body3;
import io.swagger.client.model.Body4;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PricesApi
 */
@Ignore
public class PricesApiTest {

    private final PricesApi api = new PricesApi();

    
    /**
     * Get price of the product
     *
     * Returns the current list and sale prices of the searched product.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPriceProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        InlineResponse2002 response = api.getPriceProductBySku(clientId, accessToken, sku);

        // TODO: test validations
    }
    
    /**
     * Save a newly created price of the product
     *
     * Saves a new list and/or sale price of a product with no previous price set.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void savePriceProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        Body4 body = null;
        api.savePriceProductBySku(clientId, accessToken, sku, body);

        // TODO: test validations
    }
    
    /**
     * Update price of the product
     *
     * Updates the list and/or sale price of the product.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePriceProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        Body3 body = null;
        api.updatePriceProductBySku(clientId, accessToken, sku, body);

        // TODO: test validations
    }
    
}
