/*
 * API Marketplace Grupo Netshoes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body5;
import io.swagger.client.model.Body6;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StocksApi
 */
@Ignore
public class StocksApiTest {

    private final StocksApi api = new StocksApi();

    
    /**
     * Get stock of the product
     *
     * Returns the current stock quantity of the product.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStockProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        InlineResponse2003 response = api.getStockProductBySku(clientId, accessToken, sku);

        // TODO: test validations
    }
    
    /**
     * Save a newly created stock quantity of the product
     *
     * Saves a new stock quantity of a product with no previous stock set.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveStockProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        Body6 body = null;
        api.saveStockProductBySku(clientId, accessToken, sku, body);

        // TODO: test validations
    }
    
    /**
     * Update stock of the product
     *
     * Updates the stock quantity of the product.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateStockProductBySkuTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String sku = null;
        Body5 body = null;
        api.updateStockProductBySku(clientId, accessToken, sku, body);

        // TODO: test validations
    }
    
}
